### PR TITLE
Fix: Chinese list line spacing

### PR DESCRIPTION
**Pull request by billypchan**
fix the issue https://github.com/wireapp/wire-ios/pull/3481.
Insert font attribute for the line break after paragraph.

### CODE REVIEW

**Review by alexaubry — APPROVED** [review]

**Comment by alexaubry** [comment]
Would be nice to contribute this one back to the Down project 😃

**Review by johnxnguyen — APPROVED** [review]

**Comment by johnxnguyen** [comment]
I'll make a note to include this when I finish implementing the styler on the original Down project.

**Comment by billypchan** [comment]
@zenkins release patch

**Comment by johnxnguyen** [comment]
@billypchan I don't think Jenkins listens to this repo, you'll have to release manually.

**Pull request merged**
